# Default values for template-node-typescript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

############################################
# Deployment.metadata.name
# Deployment.metadata.lables.app
# Deployment.spec.selector.matchLabels.app
# Deployment.template.metadata.labels.app
# Deployment.spec.containers.name
# ++++++++++++++++++++++++++++++++++++++++++
# Service.metatdata.name
# Service.metadata.lables.app
# Service.spec.selector.app
name: keycloak

############################################
# Deployment.metadata.namespace
# Service.metadata.namespace
namespace: cloud-native-starter

############################################
# Deployment.template.metadata.version
version: v1

############################################
# Deployment.spec.template.spec.containers.image
image: "quay.io/keycloak/keycloak:10.0.2"

############################################
# Deployment.spec.template.spec.containers.ports.containerPort
ports:
  containerPortHTTP: "8080"
  containerPortHTTPS: "8443"

############################################
# Service.spec.ports.port
# Service.spec.ports.targetPort
service:
  portHttp: "8080"
  portHttps: "8443"

############################################
# Deployment.spec.template.spec.containers.env.name:
env:
  KEYCLOAK_USER: "admin"
  KEYCLOAK_PASSWORD: "admin"
  PROXY_ADDRESS_FORWARDING: "true"
