# Default values for template-node-typescript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

############################################
# Deployment.metadata.name
# Deployment.metadata.lables.app
# Deployment.spec.selector.matchLabels.app
# Deployment.template.metadata.labels.app
# Deployment.spec.containers.name
# ++++++++++++++++++++++++++++++++++++++++++
# Service.metatdata.name
# Service.metadata.lables.app
# Service.spec.selector.app
name: web-api

############################################
# Deployment.metadata.namespace
# Service.metadata.namespace
namespace: cloud-native-starter

############################################
# Deployment.template.metadata.version
version: v1

############################################
# Deployment.spec.template.spec.containers.image
image: quay.io/tsuedbroecker/web-api-secure:v1

############################################
# Deployment.spec.template.spec.containers.ports.containerPort
ports:
  containerPort: 8081

############################################
# Service.spec.ports.port
service:
  port: 8081

############################################
# ConfigMap.data.QUARKUS_OIDC_AUTH_SERVER_URL
QUARKUS_OIDC_AUTH_SERVER_URL: "http://keycloak:8080/auth/realms/quarkus"